import { existsSync, mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, join, relative } from "node:path";
import { fileURLToPath } from "node:url";
import type { Ctx } from "./ctx.ts";
import { buildDriftReport } from "./drift.ts";
import { currentTree, evidenceVerdict } from "./evidence.ts";
import { gitHead } from "./git.ts";
import { fail, ok, usage, type CmdResult } from "./result.ts";
import { assertSafeTree, loadSpecModel, repoRelative, safePath, sourceFile } from "./spec-map.ts";
import { buildTrace } from "./trace.ts";

export function atlasData(ctx: Ctx) {
  const model = loadSpecModel(ctx);
  if (model.problems.length) throw new Error(`source problems: ${model.problems.join("; ")}`);
  assertSafeTree(ctx, "tests");
  const records = repoRelative(ctx, ctx.records);
  assertSafeTree(ctx, `${records}/features`);
  safePath(ctx, `${records}/evidence/verify.json`);
  safePath(ctx, `${records}/evidence/junit.xml`);
  const drift = buildDriftReport(ctx, model);
  // The existing evidence verdict reconciles tree/report hashes. A test-name
  // mapping below remains a mapping even when the overall run was successful.
  const verdict = evidenceVerdict(ctx);
  const trace = buildTrace(ctx).rows.map(row => ({ ...row, tests: row.tests.map(p => repoRelative(ctx, p)) }));
  const sourcePaths = [...new Set([
    model.requirementFile, ...model.features.flatMap(f => [f.plan, ...f.drafts, ...f.implementation.map(r => r.path), ...f.related.map(r => r.path)]),
    ...trace.flatMap(r => r.tests), ...drift.rows.flatMap(r => r.previous ? [r.previous.evidence.path] : []),
  ])];
  const links = sourcePaths.filter(path => !sourceFile(ctx, path).problem);
  return {
    schemaVersion: 1, generatedAt: new Date().toISOString(), commit: gitHead(ctx), codeTree: currentTree(ctx),
    model, drift, trace, links,
    evidence: verdict.ok
      ? { current: true, source: verdict.via, note: "当前内容树有通过且对账的功能证据；不代表每个 AC 自动通过或用户验收。" }
      : { current: false, source: "", note: `证据缺失、失败或已过期：${verdict.gaps.join("; ")}` },
  };
}

/** Exported JSON is data, never HTML or executable repository-authored script. */
function embedJson(value: unknown): string {
  return JSON.stringify(value).replace(/</g, "\\u003c").replace(/>/g, "\\u003e").replace(/&/g, "\\u0026").replace(/\u2028/g, "\\u2028").replace(/\u2029/g, "\\u2029");
}

export function runAtlas(ctx: Ctx, args: string[]): CmdResult {
  if (args.includes("--json")) {
    if (args.length !== 1) return usage("usage: gate atlas --json | [--out <repo-relative.html>]");
    try { return ok(JSON.stringify(atlasData(ctx), null, 2) + "\n"); }
    catch (error) { return fail(`atlas: ${(error as Error).message}\n`); }
  }
  if (args.length && (args.length !== 2 || args[0] !== "--out")) return usage("usage: gate atlas [--out <repo-relative.html>] | --json");
  const output = args[1] ?? `${repoRelative(ctx, ctx.records)}/evidence/atlas.html`;
  try {
    if (!output.endsWith(".html")) return usage("atlas output must end in .html");
    const path = safePath(ctx, output);
    const marker = "<!-- keel-atlas-generated-v1 -->";
    if (existsSync(path) && !readFileSync(path, "utf8").startsWith(marker)) return fail("refusing to overwrite a file not generated by gate atlas\n");
    const data = atlasData(ctx);
    const sourcePaths = [
      data.model.requirementFile, ...data.model.features.flatMap(f => [f.plan, ...f.drafts, ...f.implementation.map(r => r.path), ...f.related.map(r => r.path)]),
    ];
    if (sourcePaths.includes(output)) return fail("atlas output overlaps a source file\n");
    const assets = dirname(fileURLToPath(import.meta.url));
    const css = readFileSync(join(assets, "atlas.css"), "utf8");
    const client = readFileSync(join(assets, "atlas-client.js"), "utf8");
    const rootPrefix = relative(dirname(path), ctx.root).replace(/\\/g, "/") || ".";
    const html = `${marker}
<!doctype html>
<html lang="zh-CN"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<meta http-equiv="Content-Security-Policy" content="default-src 'none'; script-src 'unsafe-inline'; style-src 'unsafe-inline'; img-src data:; connect-src 'none'; base-uri 'none'; form-action 'none'">
<title>keel · 需求与实现</title><style>${css}</style></head>
<body><main id="atlas">
<header><p class="eyebrow">KEEL / SPEC ATLAS</p><h1>从意图，看到实现。</h1><p id="snapshot"></p></header>
<section class="notice" aria-label="证据状态"><span id="evidence"></span><details><summary>如何理解这些状态</summary><p>这是生成时的只读快照。内容对齐仅表示与上次明确复核一致，不证明语义正确。测试名称是静态映射，summary 是完成声明；manual 与 proxy 仍须核对实际证据。更新后重新运行 gate atlas。</p></details></section>
<div class="toolbar"><label>搜索需求、功能或路径<input id="search" type="search" placeholder="例如 REQ-029、F25 或 drift.ts"></label><label>漂移状态<select id="state"><option value="all">全部状态</option><option value="review">待复核</option><option value="aligned">内容对齐</option><option value="unmapped">未接入</option></select></label><button type="button" id="reset">重置视图</button></div>
<p id="results" role="status" aria-live="polite"></p>
<section id="unmapped-requirements" aria-label="尚未映射到功能的需求"></section>
<section id="graph" aria-label="需求—功能—技术实现关联">
<svg id="edges" aria-hidden="true"></svg>
<section class="column"><h2>01 / 需求</h2><p class="hint">所选功能承诺什么</p><div id="requirements" class="nodes"></div></section>
<section class="column"><h2>02 / 功能</h2><p class="hint">选择功能，展开两侧关系</p><div id="features" class="nodes"></div></section>
<section class="column"><h2>03 / 技术实现</h2><p class="hint">实线为实现，虚线为相关引用</p><div id="files" class="nodes"></div></section>
</section>
<section id="detail" aria-live="polite"></section>
<details id="source-problems"><summary>来源与治理问题</summary><pre id="problems"></pre></details>
<footer>同一份需求与计划 · 无服务、无外部依赖 · 导出不会修改规格、复核记录或 Git 暂存区</footer>
</main><script id="atlas-data" type="application/json">${embedJson({ ...data, rootPrefix })}</script><script>${client}</script></body></html>\n`;
    mkdirSync(dirname(path), { recursive: true });
    writeFileSync(path, html, "utf8");
    return ok(`atlas: ${path}\nread-only snapshot; ${data.model.features.length} features; ${data.drift.needsReview} need review; source links require the repository\n`);
  } catch (error) { return fail(`atlas: ${(error as Error).message}\n`); }
}
