import { existsSync, readdirSync, statSync } from "node:fs";
import { join } from "node:path";

export const SKILL_CATALOG = [
  "k-init",
  "k-migrate",
  "k-new",
  "k-impl",
  "k-bugfix",
  "k-change",
  "k-review",
  "k-accept",
  "k-retro",
  "k-handoff",
  "k-status",
  "k-grill",
  "k-research",
  "k-decide",
  "k-evidence",
  "k-log",
] as const;

/** Explicit-entry lifecycle skills retained from DEC-170. Invocation never grants mutation authority. */
export const USER_SKILLS = ["k-init", "k-migrate", "k-accept"] as const;

/** Ordinary task workflows are discoverable without requiring a magic skill name (CHG-017). */
export const MODEL_SKILLS = SKILL_CATALOG.filter(
  (name) => !(USER_SKILLS as readonly string[]).includes(name),
);

/**
 * DEC-170: Codex reads `agents/openai.yaml` beside SKILL.md for its display name and
 * whether the skill may be invoked implicitly (OpenAI Codex skills docs; RES-904 §7).
 * Generated by `gate sync`; after CHG-011 nothing machine-checks it.
 */
export function openaiYamlFor(name: string, description: string): string {
  const first = (description.split(/(?<=\.)\s+/)[0] ?? description).trim();
  const esc = (s: string): string => s.replace(/\\/g, "\\\\").replace(/"/g, '\\"');
  const implicit = (MODEL_SKILLS as readonly string[]).includes(name);
  return `interface:\n  display_name: "${esc(name)}"\n  short_description: "${esc(first)}"\npolicy:\n  allow_implicit_invocation: ${implicit}\n`;
}

export function listSkillDirs(skillsRoot: string): string[] {
  if (!existsSync(skillsRoot)) return [];
  return readdirSync(skillsRoot)
    .filter((n) => n.startsWith("k-"))
    .filter((n) => {
      try {
        return statSync(join(skillsRoot, n)).isDirectory();
      } catch {
        return false;
      }
    })
    .sort();
}
